title: My Blog
author: Abdulrazak
email: dulleycubic419@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just an IT student who is interested technology staffs

# social linkste
twitter_username: abdulrazak_mus # DO NOT include the @ character, or else the build will fail!
github_username:  Abdulrazakmus # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


theme: minima
